### ISSUE TITLE
Set up a preprocessing pipeline

### ISSUE THREAD

**Issue by mkorvas** [jeroendecroos/kaggle_transfer_learning_on_stack_exchange_tags#3]
Set up a preprocessing pipeline, perhaps with some classes providing modest abstraction of the data.

**Comment by mkorvas** [comment]
We have this done, right?

**Comment by jeroendecroos** [comment]
A basic implimentation yes.
We might want a more configurable setup so we can experiment with different cleaning mechanism (e.g. we might not want to remove some punctuations)
I'll close this one, if we want some other functionality, we can create a new ticket.
